# Docker Compose file for the dev environment.

version: '3.1'

services:
  db:
    image: docker.io/mariadb:lts
    container_name: yaams-db
    networks:
      -  "yaams"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: start123

  phpmyadmin:
    image: phpmyadmin
    container_name: yaams-phpmyadmin
    networks: 
      - "yaams"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

networks:
  yaams:
    name: yaams
    external: true